### ISSUE TITLE
Text content properties should have "raw" and "rendereded" fields 

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#12]
About the Course's access period object:
opens and closes message field in the specs contain shortcodes...
This makes me thing that we should split all the properties which can contain shortcodes (or blocks?!) into `raw` and `rendered` with the second only accessible in `edit` context, exactly as we do with the `title`,`content`,`excerpt`.
What do you think?

_Originally posted by @eri-trabiccolo in https://github.com/gocodebox/lifterlms-rest/issues/6#issuecomment-507026875_

**Comment by thomasplevy** [comment]
Resolved in latest commit mess

**Comment by thomasplevy** [comment]
@eri-trabiccolo all course fields updated accordingly.

Also note that `capacity` and `capacity_message` have been combined into an object to keep these dependent props organized together.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
specs need to update:
Enrollment opens/closes messages should be objects with `raw` `rendered` fields.

**Comment by thomasplevy** [comment]
I think you're looking at the request instead of the response

Compare values in the 200 OK response at https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses/get with the request parameters for https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses/post

Create & Update requests expect a string, Reads return the object.

**Comment by eri-trabiccolo** [comment]
Yes you're right.
I've scrolled the page too much. :/
Anyway I've already implemented the schema the correct way, just wanted to report the issue in the spec, which is not an issue. Sorry for this fake alarm.

**Comment by thomasplevy** [comment]
no problem
