### ISSUE TITLE
Return `sales_page_url` if context = edit

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms-rest#130]
If the condition on [LLMS_REST_Courses_Controller line 659](https://github.com/gocodebox/lifterlms-rest/blob/7a59d8ab4f90ce50d6fde951eee7c4f91e7b541c/includes/server/class-llms-rest-courses-controller.php#L659) is true, then line 662 will not be executed, even if `context` is `edit`.

**Comment by eri-trabiccolo** [comment]
Right!
Stupid me :)
