### ISSUE TITLE
How many nesting levels for our api fields?

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#14]
![Schermata 2019-07-02 alle 17 24 48](https://user-images.githubusercontent.com/7689242/60525271-5abd0f80-9cee-11e9-982e-980731222ddc.png)

I think we have to "define" how much nested our fields can be, for two reasons:
1) rules :D which means "practical in the future"
2) "practical now"
There's a core helper that, given a response data (array) and a context (and implicitly a schema), will filter the "response" by context:
https://github.com/WordPress/WordPress/blob/5.2.2/wp-includes/rest-api/endpoints/class-wp-rest-controller.php#L233
As you can see it will only work with a maximum of one nesting level (it will work with the 'content' => ['raw','rendered'] structure type). 

I happen to use it, of course we can override it, and we'll fix the point 2), but are we sure it'll be a good choice for the future?

Of course I see that helper is kinda limited and we can possibly do it better.

**Comment by thomasplevy** [comment]
All nested properties will switch to top-level properties, will update today
