### ISSUE TITLE
On student creation/registration no welcome email is sent

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#142]
I guess because we don't fire the `lifterlms_user_registered` action...

Reported on HS-106676

**Comment by thomasplevy** [comment]
This is a bug, yes. Student user registration *should* trigger core actions (and notifications).

Note that the core controller where the actions would be triggered is shared between student creation and instructor creation. These core actions should only be triggered when creating students *not* when creating instructors.

**Comment by thomasplevy** [comment]
HS-122344

**Comment by thomasplevy** [comment]
@eri-trabiccolo want to bundle this into your priorities while working on #145?

**Comment by eri-trabiccolo** [comment]
I need to map the resource's props to the `data` expected by those actions.
I'm not going to finish this today :|

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm going to hold the release of beta.12 (#162) to include this with the release

**Comment by eri-trabiccolo** [comment]
Yes, sorry for being late on this :(

**Comment by thomasplevy** [comment]
No worries, just nudging you that this is a priority :-p

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I've spent quite some time on this and I think that the best thing to do here is to fire a specific action when the student is created via rest-api, and hook to that in the notifications/engagements controllers.
Why so?
We should theoretically fire these actions, right?
https://github.com/gocodebox/lifterlms/blob/3.38.2/includes/class.llms.person.handler.php#L765-L766

that are used here:
https://github.com/gocodebox/lifterlms/blob/3.38.2/includes/notifications/controllers/class.llms.notification.controller.student.welcome.php#L39
https://github.com/gocodebox/lifterlms/blob/3.38.2/includes/class.llms.engagements.php#L82
https://github.com/gocodebox/lifterlms/blob/3.38.2/includes/class.llms.engagements.php#L290

but also here:
https://github.com/gocodebox/lifterlms/blob/3.38.2/includes/forms/controllers/class.llms.controller.registration.php#L21

BUT those hooks are historically used to allow for registration/checkout/update fields customizations (meta update):
https://lifterlms.com/docs/add-custom-fields-lifterlms-checkout-open-registration/
But our api won't use the same filters to add new user fields.

Also the data passed to that filter in front is the form data that shows some differences compared to our api.
Let's say address fields are hidden on front, the `data` passed to that hook won't contain the "address related" fields when you perform a registration on front, and that is for sure. So we should _at least_ combine the rest-api data with the available registration fields, and I don't even know if that makes any sense, because actually the `data` contains also the nonce, the action, (voucher field), password and email confirmation fields ecc.

----------
btw there are also a couple of other fields that we don't include in our schema:
- phone
- agree_to_terms (?)
----------

I know I know that internally we shouldn't have any problem with this, and that it doesn't impact on the main goal here, but it looks to me as something wrong passing such a different dataset.

So the idea is to just fire an action hook:
`		do_action( 'llms_rest_student_registered', $student_id, $request );`
when creating a new student, and listen to it here:
https://github.com/gocodebox/lifterlms/blob/3.38.2/includes/notifications/controllers/class.llms.notification.controller.student.welcome.php#L39
https://github.com/gocodebox/lifterlms/blob/3.38.2/includes/class.llms.engagements.php#L82
https://github.com/gocodebox/lifterlms/blob/3.38.2/includes/class.llms.engagements.php#L290


I'm moving in this direction, what do you think?

**Comment by thomasplevy** [comment]
Yea this makes sense to me

**Comment by eri-trabiccolo** [comment]
I'm going to push the core part in a moment.
