### ISSUE TITLE
Spec: Update Students resource's documentation adding the `context` to the properties.  

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#143]
reported: https://wordpress.org/support/topic/api-request-error-11/#post-12320742

**Comment by thomasplevy** [comment]
Am I missing something?

![Screenshot_2020-02-04_16-24-19](https://user-images.githubusercontent.com/1290739/73799429-d68ea700-476a-11ea-9610-5d37964778c5.png)

**Comment by eri-trabiccolo** [comment]
I was probably inaccurate.

E.g.
https://github.com/gocodebox/lifterlms-rest/blob/1.0.0-beta.9/includes/abstracts/class-llms-rest-users-controller.php#L247

The username property is available only in `edit` context, but the student's resource documentation doesn't mention that, and so on...

![Schermata 2020-02-05 alle 09 43 58](https://user-images.githubusercontent.com/7689242/73825340-19e52600-47fc-11ea-98c9-362e9eed2df8.png)

**Comment by eri-trabiccolo** [comment]
also reported/asked here on hs # 112601

**Comment by thomasplevy** [comment]
@eri-trabiccolo I spent a while the other day trying to figure out how to provide conditional examples of information provided in various contexts. This is an issue that has come up a few times now with this particular endpoint but will occur across many rest endpoints.

Do you have any ideas how to best document what displays in what context?

The WordPress core essentially ignores this (like we do currently) but I cannot come up with a good way to illustrate this without adding a ton of extra TEXT to each item that's returned conditionally based on context

**Comment by thomasplevy** [comment]
@eri-trabiccolo I think I just figured it out, I'm going to push up a PR in a sec to see what you think.

**Comment by eri-trabiccolo** [comment]
@thomasplevy what happened to this?

**Comment by thomasplevy** [comment]
@eri-trabiccolo I don't know... I'll have to dig through my local branches and see... If my memory serves me right I couldn't figure it out but I'm not sure why I posted that I did

**Comment by thomasplevy** [comment]
@eri-trabiccolo I don't have anything locally, I'm remembering now that I started to work on updating it using this as a template but it actually doesn't work as I was expecting: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

**Comment by eri-trabiccolo** [comment]
ok @thomasplevy thanks!
