### ISSUE TITLE
Students: Allow students filtering by email address

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#145]
Add `search` and `search_columns` request parameters to the LIST students endpoint (https://developer.lifterlms.com/rest-api/#tag/Students/paths/~1students/get)

These parameters should map to the underlying `WP_User_Query()` (https://developer.wordpress.org/reference/classes/WP_User_Query/prepare_query/)

**Comment by eri-trabiccolo** [comment]
HS-121145

**Comment by thomasplevy** [comment]
HS-122344

**Comment by eri-trabiccolo** [comment]
remember:

> The only other thing is that the context should affect the search_columns

**Comment by thomasplevy** [comment]
default search columns available on a `WP_User_Query`: 'ID', 'user_login', 'user_email', 'user_url', 'user_nicename', 'display_name' [source](https://developer.wordpress.org/reference/classes/WP_User_Query/prepare_query/)
