### ISSUE TITLE
REST API uses `billing_postcode` but `billing_zip` used everywhere else in LLMS code

### ISSUE THREAD

**Issue by vertika1** [gocodebox/lifterlms-rest#155]
### Reproduction Steps

+ Create a student using `/wp-json/llms/v1/students` while passing non-empty value for `billing_postcode`

### Expected Behavior

+ Billing Zip Code field on the user profile page (back-end) and Zip Code on the student `edit-account` page (front-end) to contain the value that was passed in `billing_postcode`

### Actual Behavior

+ Billing Zip Code and Zip Code are both empty in the back-end and front-end, respectively

### Information

I was trying to create students and noticed the zip code fields weren't populated even though I was passing in a value for `billing_postcode` per the schema spec. A usermeta record is created with a meta_key `llms_billing_postcode`, but `billing_zip` or `llms_billing_zip` are used everywhere else in the LifterLMS code base. 

I apologize in advance if I didn't provide enough details, so please forgive me as this is my first ever bug report (just created my Github account today).

**Comment by eri-trabiccolo** [comment]
@vertika1 
many thanks for reporting this, it's a bug indeed!

> I apologize in advance if I didn't provide enough details, so please forgive me as this is my first ever bug report (just created my Github account today).

I've been able to reproduce the issue you reported, so thanks agin for this bug report! :D
