### ISSUE TITLE
Handle custom fields

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#157]
https://lifterlms.slack.com/archives/CCESQHE82/p1585632416015700

we should handle custom fields (meta) and registered rest fields in general.
It was not implemented for the early beta releases because of a conflict with the instructors and visibility fields registered in llms-blocks, but it's something easy to fix. So let's do it and... mostly... let's dance!

**Comment by thomasplevy** [comment]
We should include user meta data in this as well

**Comment by eri-trabiccolo** [comment]
HS-159403

**Comment by thomasplevy** [comment]
Custom user fields from LifterLMS Custom Fields add-on should be accessible via user endpoints (https://github.com/gocodebox/lifterlms-custom-fields/issues/42)

**Comment by eri-trabiccolo** [comment]
Working on this, I'm trying to abstract this as much as possible (more work on abstraction must be done), this is the plot:
https://github.com/eri-trabiccolo/lifterlms-rest/tree/issue/157
