### ISSUE TITLE
[GET]/lessons returning empty []

### ISSUE THREAD

**Issue by musangowope** [gocodebox/lifterlms-rest#161]
### Reproduction Steps
Background Context:
Running wordpress on `http://localhost:8080` (wp-json is active)
--
1. Create lessons and publish
2. Create Course and publish
3. Open Course builder of created course 
4. Create Sections and add created lessons to created sections 
5. Use insomnia to test endpoint `/lessons`  with get request
`http://localhost:8080/wp-json/llms/v1/lessons`
with headers
`X-LLMS-CONSUMER-KEY: '...'`
`X-LLMS-CONSUMER-CONSUMER: '...'`

Video
https://www.loom.com/share/e6d44df1d3054499880a72bf6a7ead2c

### Expected Behavior
returns all **published** lessons 

### Actual Behavior
returns an empty array 

### Error Messages / Logs
```
GET /wp-json/llms/v1/lessons HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/7.1.1
> Cookie: _wp_session=8d1f2b89d0e53dcb1598c05ef57d3e4e%7C%7C1590048699%7C%7C1649621499
> X-LLMS-CONSUMER-KEY: ck_7e28161ec74debb732af1bfb71ebd1a4aa5ad6bb
> X-LLMS-CONSUMER-SECRET: cs_28a51658d0b1c91f2db8caccb2fcc6c99a666eb9
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200 OK
< Date: Wed, 20 May 2020 22:31:54 GMT
< Server: Apache/2.4.38 (Debian)
< X-Powered-By: PHP/7.3.16

* Replaced cookie _wp_session="8d1f2b89d0e53dcb1598c05ef57d3e4e%7C%7C1590048699%7C%7C1649621499" for domain localhost, path /, expire 1590048699

< Set-Cookie: _wp_session=8d1f2b89d0e53dcb1598c05ef57d3e4e%7C%7C1590048699%7C%7C1649621499; expires=Thu, 21-May-2020 08:11:39 GMT; Max-Age=34785; path=/
< X-Robots-Tag: noindex
< Link: <http://localhost:8080/wp-json/>; rel="https://api.w.org/"
< X-Content-Type-Options: nosniff
< Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
< Access-Control-Allow-Headers: Authorization, Content-Type
< X-WP-Total: 4
< X-WP-TotalPages: 1
< Allow: GET
< Vary: Origin
< Content-Length: 2
< Content-Type: application/json; charset=UTF-8
```
### System Information

<details>
<summary>System Report</summary>
  
```
`
### wp-core ###

version: 5.4.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: 39.44 MB (41358562 bytes)
uploads_path: /var/www/html/wp-content/uploads
uploads_size: 476.35 KB (487779 bytes)
themes_path: /var/www/html/wp-content/themes
themes_size: 3.79 MB (3975557 bytes)
plugins_path: /var/www/html/wp-content/plugins
plugins_size: 11.47 MB (12030049 bytes)
database_size: 2.25 MB (2359296 bytes)
total_size: 57.42 MB (60211243 bytes)

### wp-active-theme ###

name: Twenty Nineteen (twentynineteen)
version: 1.5
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, responsive-embeds, widgets
theme_path: /var/www/html/wp-content/themes/twentynineteen

### wp-themes-inactive (2) ###

Twenty Seventeen: version: 2.3, author: the WordPress team
Twenty Twenty: version: 1.2, author: the WordPress team (latest version: 1.3)

### wp-plugins-active (1) ###

LifterLMS: version: 3.38.1, author: LifterLMS (latest version: 3.38.2)

### wp-plugins-inactive (2) ###

Akismet Anti-Spam: version: 4.1.4, author: Automattic (latest version: 4.1.5)
Hello Dolly: version: 1.7.2, author: Matt Mullenweg

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 12
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 5.3.0-51-generic x86_64
httpd_software: Apache/2.4.38 (Debian)
php_version: 7.3.18 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.64.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.29
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`
```

</details>

### Browser, Device, and Operating System Information

Browser: Chrome
OS: Ubuntu 18.4
Gigabyte Saber 15

**Comment by thomasplevy** [comment]
@musangowope 

Thanks for the bug report!

Unfortunately based on the information provided we're unable to recreate (you slacked me about this about an hour ago and I've already confirmed that this is working as expected in a local test environment).

A few follow up questions to help us figure out what's going wrong here:

**1. Plugin and theme conflicts**

You've neglected to provide your system report which, while possibly seeming non-essential -- is essential. It helps us rule out plugin and theme conflicts which we generally assume you'll know to do on your own but cannot guarantee.

So, have you ruled out plugin and theme conflicts? If not, please disable all plugins except LifterLMS and switch to a default theme like twentytwenty and let us know if the issue is still recreatable in this environment.

**2. Are you using the latest version of LifterLMS?**

If not, please try the latest version and let us know.

**3. Triple and Quadruple check your keys**

3A. What is the role of the user who owns the keys?
3B. Are you certain that your keys were copied correctly? Are they working for other endpoints, for example?

**Comment by thomasplevy** [comment]
@musangowope 

@eri-trabiccolo noted that this is very likely an authentication issue related to not using an SSL certificate, a requirement of our REST API: https://developer.lifterlms.com/rest-api/#section/Introduction/Requirements

If this is the case you should be able to add a self-signed SSL cert on your localhost and use the API as expected.

Let us know if this helps

**Comment by musangowope** [comment]
@thomasplevy updated my wordpress information. There seems to be something wrong with my docker wordpress instance. I tried getting lessons from my trial account lifterlms(the hosted wordpress site) and it works
