### ISSUE TITLE
Authentication & API Credentials

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#2]
The API will implement HTTP Basic Authentication (consumer key/secret) via request headers.

As a fallback for servers which cannot properly parse request headers the consumer key/secret may be passed as query string variables, for example `POST /students?consumer_key={$key}&consumer_secret={$secret}`

The API will only accept HTTPS requests.

API keys will be stored in a custom table, `wp_lifterlms_api_keys` with the following structure:

```sql
  `key_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `description` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `permissions` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `consumer_key` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `consumer_secret` char(43) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_access` datetime DEFAULT NULL,
  PRIMARY KEY (`key_id`),
  KEY `consumer_key` (`consumer_key`),
  KEY `consumer_secret` (`consumer_secret`)
```

Each key will belong to a WP_User (related via `user_id`)

Permissions are an enum: `read`, `write`, `read_write`, this context will be taken into account during requests. EG: a key with `read` permissions will receive a `403 Forbidden` response when attempting to create a resources and a key with `write` permissions will receive a `403 Forbidden` when attempting to read resources. A `read_write` key will have full permissions.

Furthermore, user permissions and capabilities will define the access. If an instructor is provided with an API key, they will not be able to preform updates on resources they don't have access to outside of their capabilities. 

Requests made to the API using cookie authentication will authenticate via the current user and provide that user with resource access based off their user roles and capabilities. 

An interface (within the WordPress admin panel) will be created to manage (CRUD) API keys.

**Comment by pondermatic** [comment]
When the consumer key/secret is passed in query variables, they may be leaked into web server logs and may be available to JavaScript via the `Referer` HTTP header. See [How Secure Are Query Strings Over HTTPS?](http://blog.httpwatch.com/2009/02/20/how-secure-are-query-strings-over-https/)

**Comment by thomasplevy** [comment]
@pondermatic 

After writing this I did write the actual specification to pass these via headers rather than query variables, see the current state of the spec here: https://gocodebox.github.io/lifterlms-rest/#section/Authentication/Header-Authentication

However there's still danger in passing them this way as JS and logs could still record them.

I'm not terribly opposed to mandating basic auth to pass the keys. Allowing the keys to be passed without the use of the Authorization header seems to be a way to add compatibility for servers that have the Authorization header disabled.

WooCommerce provide the ability to pass via query string for this reason, from their docs:

> Occasionally some servers may not parse the Authorization header correctly (if you see a "Consumer key is missing" error when authenticating over SSL, you have a server issue). In this case, you may provide the consumer key/secret as query string parameters instead.

Source: https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-https

My assumption would be that we could mandate using authorization and if someone does encounter this kind of issue we could advise them to work with their host to get the issue fixed instead of providing them with a less-secure way to not have to make server fixes...

Thoughts?
