### ISSUE TITLE
Sections/lessons resources spec: add previous/next section under _links?

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#20]
Do you think would be worthwhile adding links to the previous/next section resource under _links?

**Comment by thomasplevy** [comment]
right now `GET` request to collection lists return next/prev/last/first resource links via the `Link` header. I pulled this from the WP Core's api. None of their `_links` link to these kind of relations.

I think it makes sense when requesting a single resource (EG: `/lessons/123` or `sections/456` you should be able to see the next/prev/first/last resources in that collection. However, I'm not sure the best way to implement this.

The collection itself doesn't have an `_links` array, so it *has* to return this in the header unless we change the lists to return an object like:

```json
{
"items": [ ... ],
"links": [ ... ],
}`

This would be how Stripe's API handles things and it's quite nice (you can grab all your related resources from the body instead of having to look to headers.

However, that departs from WP core patterns that WP devs may (or may not) be familiar with.

Since our single resources already have a `_links` array we could easily add these links to that array.

Does it seem okay to return these links for single resources in the `_links` in the body or should single resources also return these in the header?

If we put them in the `_links` you'll actually be able to read these related resources when pulling data from a list request. If we put them in the header you can only get these relations during a request to a single resource.

I think I needed to type this all out to come to the conclusion that __you're right, we should add these__ and should add them to lessons too.

I'll update spec accordingly later.

**Comment by eri-trabiccolo** [comment]
:D 
Just to give you more information on my "request".
I thought we needed this for the sections because the sections have an order within a course so the next/prev made sense.
The section's next/prev depends on the `order` property, hence these links will basically gather the URL from section's object get_next/get_prev.
This was my idea... Does it still make sense to you?

**Comment by thomasplevy** [comment]
Yep, I understood that being the reason for adding these
