### ISSUE TITLE
Spec: Missing response and response samples for delete endpoints

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#216]
E.g.

- [x] **Lessons**: https://developer.lifterlms.com/rest-api/#tag/Lessons/paths/~1lessons~1{id}/delete
  - [x] Missing 200 response
  - [x] Missing 200 sample
- [x] **Memberships**: https://developer.lifterlms.com/rest-api/#tag/Memberships/paths/~1memberships~1{id}/delete
  - [x] Missing 200 response
  - [x] Missing 200 sample

(updated according to https://github.com/gocodebox/lifterlms-rest/issues/216#issuecomment-756254183)

**Comment by thomasplevy** [comment]
Deletions never have a 200 response and 204s have no content

**Comment by eri-trabiccolo** [comment]
99% stupid me, I got confused, although...
Right, deletions never have 200 response, so we have to amend the course specs:
https://developer.lifterlms.com/rest-api/#tag/Courses/paths/~1courses~1{id}/delete
But 204s do have content when the resource is not completely deleted but only trashed.
So the course's 200 sample should actually be the sample for the 204 (when `force` is `true`)

@thomasplevy ^

**Comment by thomasplevy** [comment]
Sorry, you're right, if we move to the trash there *is* a 200 response.

If it's deleted (not trashed) it's a 204 (with no response, and therefore no response sample)
