### ISSUE TITLE
Stop returning an error when updating resources properties with a new value equal to the saved one

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#222]
This i basically due to https://github.com/gocodebox/lifterlms/issues/909

But we decided that, since this is really a question concerning the REST API, we should just handle this here.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I dug a little bit into this, and realized that doing all the "treatment" in the rest api would be uncomfortable.
That's because we scrub the properties before actually passing them to `update_post_meta()`. 
So we should compare the scrubbed new value with the raw value stored the db... 
But the scrubbing logic is something internal to the post model.(1)

And that it's not even enough, because the value that we pass to `update_post_meta()` is treated internally in `update_metadata()` before comparing it with the db value. (2)

So the idea is:
1) the comparison should be done in the core abstract post model, on demand, either with a filter or passing another parameter to `set_bulk()`
2) Implement this logic when comparing (always in the core abstract post model):
https://github.com/WordPress/WordPress/blob/5.6.1/wp-includes/rest-api/fields/class-wp-rest-meta-fields.php#L370-L376

thumbs up?

**Comment by thomasplevy** [comment]
@eri-trabiccolo This makes sense and I think I give it a thumbs up...

The whole logic of the whole thing is starting to feel really complicated though.... The method(s) are really complicated already... adding more logic feels wild but maybe that's what we need to do... I can't come up with any alternatives.

**Comment by eri-trabiccolo** [comment]
unfortunately we both know that of course this is something the wp core should do...

**Comment by thomasplevy** [comment]
yea... you're right... okay :+1:
