### ISSUE TITLE
LifterLMS API questions

### ISSUE THREAD

**Issue by oleksandr-rapiy** [gocodebox/lifterlms-rest#225]
Hello everyone, sorry for disturbing you. But I need some help with LifterLMS.

**Does the LifterLMS stripe plugin provide API to work?**

The main point of this, I already have a website with LifterLMS and LifterLMS stripe plugins, and **I need to create another small service where I can buy courses and so on. How can I do that?**

_**Stack technologies: .Net**_ 

Thanks.

**Comment by thomasplevy** [comment]
https://lifterlms.slack.com/archives/C0H1CE4SW/p1614354642006300?thread_ts=1614345613.006200&cid=C0H1CE4SW
