### ISSUE TITLE
Make post based resources "searchable"

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#248]
We should just define a property in the `LLMS_REST_Posts_Controller` called `is_searchable` and set it to `true`.

see https://github.com/gocodebox/lifterlms-groups/issues/173

**Comment by thomasplevy** [comment]
:+1:

**Comment by thomasplevy** [comment]
I'm okay with blanket enabling searching for all post resources -- I think it should be appreciated and sensible on all existing post resources we currently have
