### ISSUE TITLE
Need an additional test case class in the framework specific to testing REST API Server methods

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#25]
https://github.com/gocodebox/lifterlms-rest/blob/f3c48dc6b90d56d074945102e3e6ec0ec8cf4672/tests/framework/class-llms-rest-unit-test-case.php#L19-L27

Since not all tests will require tests of actual REST API methods run via the actual REST API server I think a second test case should be created which extends this test case and then adds these this `setUp()` and `tearDown()` methods.

This test case could be `LLMS_REST_Server_Unit_Test_Case`

Then other tests (functions, install, custom post types, etc...) can use this generic test case and the API Server classes / controllers / etc can extend the server class which spools up and down the server reference.

**Comment by eri-trabiccolo** [comment]
At the moment `LLMS_REST_Server_Unit_Test_Case` is the old `LLMS_REST_Unit_Test_Case`
and the new `LLMS_REST_Server_Unit_Test_Case` just does nothing.

**Comment by thomasplevy** [comment]
@eri-trabiccolo perfect, I'll merge it in in a bit
