### ISSUE TITLE
Cannot remove "protected" from a course with a password:

### ISSUE THREAD

**Issue by davideneglia** [gocodebox/lifterlms-rest#261]
Hi everyone. I have my own online course portal and I'm modifyng the user interface. 
![image](https://user-images.githubusercontent.com/97828406/149654850-20ec61e6-c4dc-49b0-b8dc-742c432610f5.png)

How can I remove the word "protetto" that means that the cours has a password? I don't want to show this word.

Thank you for you help

**Comment by thomasplevy** [comment]
Hey there @davideneglia 

You'll want to use the WordPress [protected_title_format](https://developer.wordpress.org/reference/hooks/protected_title_format/) core filter to remove the "Protected" prefix that is added to password protected posts

**Comment by thomasplevy** [comment]
@davideneglia I'm going to close this out as it doesn't appear to be an issue related to the LifterLMS REST API. If you have further questions or disagree let us know and we can reopen and continue discussing.
