### ISSUE TITLE
Get Achievements and Certificates through the lifter LMS RESTAPI

### ISSUE THREAD

**Issue by BrendanSD3** [gocodebox/lifterlms-rest#262]
**Is your feature request related to a problem? Please describe.**
not sure 

**Describe the solution you'd like**
* I would like a GET method to be added to retrieve the certificates and/or Achievements for a student through the restapi
![image](https://user-images.githubusercontent.com/43151431/153846259-b0866ac6-b7a4-444c-ba2e-e13239572b14.png)

**Describe alternatives you've considered**
Open to suggestions 👍

**Comment by eri-trabiccolo** [comment]
Thanks for your feedback @BrendanSD3.
I'm going to close this in favor of #1, you can follow our progress there and let us know if you have anything further to add.

Best
