### ISSUE TITLE
Enrollment status update provides two triggers

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms-rest#278]
https://github.com/gocodebox/lifterlms-rest/blob/a12d8641a711087e5d7f95c6b211b8800644fa69/includes/server/class-llms-rest-enrollments-controller.php#L1128

`LLMS_REST_Enrollments_Controller::handle_status_update()` is giving an extra trigger argument to [`LLMS_Student::enroll()`](https://github.com/gocodebox/lifterlms/blob/6.0.0/includes/models/model.llms.student.php#L103).

The extra parameter was added in commit 99a0adb68aeb56dbebcb9a47622651506f34017e.

**Comment by eri-trabiccolo** [comment]
Niiiiice

**Comment by eri-trabiccolo** [comment]
Although this doesn't introduce any issue at the moment, right? The third parameter is superfluous, but the second parameter is correct.

**Comment by pondermatic** [comment]
That's good that the 2nd parameter is correct. Passing an extra parameter doesn't seem to generate an error.
