### ISSUE TITLE
Resource: Courses

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#29]
- [ ] [List](https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses/get)
- [ ] [Create](https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses/post)
- [ ] [Retrieve](https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses~1{id}/get)
- [ ] [Update](https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses~1{id}/post)
- [ ] [Delete](https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses~1{id}/delete)
- [ ] [List Content](https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses~1{id}~1content/get)
- [ ] [List Enrollments](https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses~1{id}~1enrollments/get)
- [ ] Test Coverage 90% or greater

**Comment by eri-trabiccolo** [comment]
Cannot although all the items, anyway if I could I would have checked all of them.
Tests and abstraction can be improved though.

Feel free to reopen if you want/need.
