### ISSUE TITLE
multiple webhooks, same topic

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms-rest#298]
We have a user that wants to know if they can use one topic to trigger a bunch of webhooks, or if there are any limitations to what a single trigger can do?

I'm inclined to say it will be fine, but wanted to double check first

**Comment by thomasplevy** [comment]
We don't have any limitations imposed on the number of webhooks you can have triggered by a single topic.

In other words: If the user wishes to create 10 different webhooks, and they all are triggered by the `course.created` topic/event, they will all fire.

When an event which triggers a webhook fires, the webhooks matching that event are queried and the webhooks will be fired one at a time

**Comment by nrherron92** [comment]
thank you <3
