### ISSUE TITLE
Students enrollments properties

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#31]
shouldn't the student_id and post_id be read-only?

**Comment by thomasplevy** [comment]
Yea you're right.

Currently the spec is sharing a schema between all 3 enrollment resources (`students/{id}/{post_id}`, `courses/{id}/enrollments`, & `memberships/{id}/enrollments`. The response object can be shared but the request arguments need to be different.

I'll fix that up today.
