### ISSUE TITLE
Courses: List course content specs

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#38]
https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses~1{id}~1content/get

- The `parent` arg doesn't make sense to me there, as we're already in the parent context.
- The `exclude` arg is missing... why?
- There's also the `password` arg, that in this case refers to the parent course, I guess. We've talked about the password protection inheritance but didn't come up with a definitive decision yet, right?!

**Comment by thomasplevy** [comment]
> There's also the password arg, that in this case refers to the parent course, I guess. We've talked about the password protection inheritance but didn't come up with a definitive decision yet, right?!

For now I'm going to remove this from this endpoint. 

If the course is password protected the content provided by this endpoint will not be available via the REST API.
