### ISSUE TITLE
Password protected posts

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#4]
Add logic to handle access to password protected llms posts.

We can look at how the WordPress core does in wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php

**Comment by eri-trabiccolo** [comment]
Same macro topic.
The WP rest api adds the sub property `protected` (bool) to the `content` and `excerpt` properties.
The reason behind this is that those properties, when a post is password protected, are returned as empty string, so, that there's no way to discriminate between an empty content and a protected content (in `view` context).
I think we should add this sub property to the specs as well.
Of course it should be added to all the properties that we want to be affected by the password protection (which at the moment are only `content` and `excerpt`).

What do you think?

**Comment by thomasplevy** [comment]
See #24
