### ISSUE TITLE
Deletions should respond with 204 and no response content

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#43]
The spec defines a `204` status code for all deletions and an empty response body, eg: https://gocodebox.github.io/lifterlms-rest/#tag/Courses/paths/~1courses~1{id}/delete

It looks like we're currently mimicking the behavior of the WP Core's `WP_REST_Posts_Controller` and responding with a `200` as well as a body containing information about the deleted post.

I'm open to adjusting this to be a 200 with the existing response body. However, in researching the spec *most* apis (outside of WP) do not respond with a body when deleting a resource.

Additionally, I came across this SO thread: https://stackoverflow.com/questions/6439416/deleting-a-resource-using-http-delete

This essentially says that you should never return a `404` on a deletion request. And should *always* return a 204 (or 200). If we were going to return a body we would not be able to return the previous content if we go with this stance. EG: If the resource never exists (and we still return the 200/4 then we wouldn't be able to pull the deleted resource's information.

I'm leaning towards switching up the current courses to be a 204 with no body. Do you agree?

Is there a good reason I'm missing why we need to return the deleted post in the request body?

The best thing I can come up with is that a client wants to "check the work of the api" against the deleted content but they shouldn't ever really need to do that (I don't think). If we tell them it's deleted that's enough. And if for some reason they *need* the deleted posts information they should preform a GET first, do whatever they need, and then delete.

Right?

**Comment by eri-trabiccolo** [comment]
You're right, I agree, and you're not missing anything.

> It looks like we're currently mimicking the behavior of the WP Core's WP_REST_Posts_Controller and responding with a 200 as well as a body containing information about the deleted post.

Yes , I started mimicking that and should've adapted it to our specs earlier! 
Thanks for the feedback and the further explanation.

**Comment by eri-trabiccolo** [comment]
So... should we also update the spec and remove the 404 response case? I guess so.

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

I wasn't really considering trash when I started writing about this. The trash is not a _semantic_ deletion. It's a status change. That means that a real delete should always force and if you want to trash you should `POST` to the resource with to update the status to `trash`.

However, most consumer's (I assume) aren't going to think "If I want to trash a resource I need to update the status" -- they're likely going to look to the `DELETE` request.

Given this... I think your initial strategy in following the core is more correct given what's expected of the API.

So let's adjust as follows:

If the resource can be trashed (sections technically can't but courses, lessons, memberships, etc... can). The resource should return a `204` with no content when the resource is **actually deleted** (`force=true`). And a `200` with a response body of the updated state of the resource (that would be the same response as a `GET` but with the newly updated status `post_status=trash`.

If a resource *does not exist* it should return with the `204` regardless of whether or not the consumer can delete that resource.

A resource like a section which cannot be trashed will not have the `200` response, only the `204` with no body.

Let me know if this makes sense to you and I'll update the spec accordingly.

**Comment by eri-trabiccolo** [comment]
I wasn't really considering trash when I started writing about this. The trash is not a semantic deletion. It's a status change. That means that a real delete should always force and if you want to trash you should POST to the resource with to update the status to trash.

**Comment by thomasplevy** [comment]
> 1. WP core sends back an 410|"already trashed" wp_error if you try to trash something already trashed (current behavior). Should we do the same? Or should we stick to a 200 with the updated resource in the response body?

I'm going to play semantics on this again... The HTTP Status definition says 

> 410 Gone client error response code indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent.

Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410

Since a trashed resource is still *technically* available (you could still `POST` to the resource to update its status to "published" and recover it) I don't know if 410 is the semantically correct response.

My understanding of idempotency is that if we trash something through a delete and trash it again through the same request we should get the same response both times.

I think. Again I'm talking semantics which do matter on some level however annoying. So I don't think this code to check the status should be executed and whether or not the item is already trashed we should still return the same 200/204 response and exclude that 410 like the WP core does.

> 2. That means that a real delete should always force and if you want to trash you should POST to the resource with to update the status to trash.
 
This was a theoretical argument I was making that I used to express that this behavior doesn't makes sense. So I agree with you:

> Does this suggest that force should be true by default? I'm not sure if we want to do this, because we're in the wp world, where, force if false by default and a deletion is not reversible...

I don't think we should force deletion when making a `DELETE`. I think we should accept that we're not actually deleting something (we're scheduling it) and have the `force` argument available (but false by default).

Whew. this got complicated. Thanks for hanging in here. I have some spec work to do. I'll get that done today. Your code looks pretty good already. The 410 I think needs to be updated yet.

**Comment by eri-trabiccolo** [comment]
I see your point.
So ok get rid of `410` and stick to `200`.
Thanks

**Comment by eri-trabiccolo** [comment]
@thomasplevy no need to re-open this, but wanted to highlight that spec still say that on course deletion can respond with a 404, which we said it should not... Or at least that's what I got.
And this should be extended to all the resources... right?

Let me know if otherwise.

Thanks.

**Comment by thomasplevy** [comment]
I have a ton of spec updates to make and I keep losing track of them since they're all buried in more complicated conversations and issues. Going to open a new issue specifically for updating the spec here so I don't forget again. Thanks.

**Comment by thomasplevy** [comment]
Spec fixed in https://github.com/gocodebox/lifterlms-rest/commit/2acb43f35423798b9e1c9dc43c5a814c4a4adc5f
