### ISSUE TITLE
Resource: Lessons

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#46]

**Comment by eri-trabiccolo** [comment]
can we say this is done?
I think we can consider this and Sections done except for the "order" thing.
See:
https://github.com/gocodebox/lifterlms-rest/issues/30#issuecomment-522751545
and my comment below it.

**Comment by thomasplevy** [comment]
Yea, we're tracking that in #78 so we can close this (I'll let you get the dopamine since you did the work)!
