### ISSUE TITLE
Unused variable `$schema` in LLMS_REST_Posts_Controller::register_routes() method.

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#53]
https://github.com/gocodebox/lifterlms-rest/blob/9228dcd15c5846a3067b84da00e78a25fa547413/includes/abstracts/class-llms-rest-posts-controller.php#L76-L86

This variable is defined but never used. I'm not user if this variable is intended to be used instead of the callback reference on line 116 (https://github.com/gocodebox/lifterlms-rest/blob/9228dcd15c5846a3067b84da00e78a25fa547413/includes/abstracts/class-llms-rest-posts-controller.php#L116) or if it was used previously and should be removed now as it's redundant.

**Comment by eri-trabiccolo** [comment]
It's something I probably was using at a certain point. Now totally redundant can be removed.
I'm removing it in my "courses" branch. Thanks!

**Comment by eri-trabiccolo** [comment]
fixed in d524980

**Comment by thomasplevy** [comment]
@eri-trabiccolo I think I messed up... the variable is used right below on line 81... and now I'm not sure what I'm looking at in your fix. I think this issue is a non issues and should be ignored... Am I wrong?

**Comment by eri-trabiccolo** [comment]
Mmm you know what? I misread this because the issue you pointed out was in the course controller, which, by chance was the file I was already looking at when I saw this issue. So I rapidly found that unused variable, but in another file...
That's what I fixed.

**Comment by thomasplevy** [comment]
Cool! Closing this then (sorry and also you're welcome)
