### ISSUE TITLE
All public taxonomies should appear under _links (?)

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#66]
https://github.com/gocodebox/lifterlms-rest/blob/f3e9ae4b1d8453444592a54e8eb05fcb15a23891/includes/abstracts/class-llms-rest-posts-controller.php#L1172

(There's another occurrence of the show_in_rest filtering but it's about updating permission, so it might even stay the way it is right now.)

**Comment by thomasplevy** [comment]
A change in LifterLMS blocks caused the filter on courses to break:

https://github.com/gocodebox/lifterlms-blocks/commit/eb20f8f520c278d3c05596af81e44c0a27deb881#diff-1a09c7233092054a9619cd53afbf16e6R58

I needed to change the blocks functionality to prevent exposing course data to unauthenticated users via GET requests to the API.

Our custom post types and taxonomies need to be shown in rest only for the purposes of making the block editor function.

But we need to deal with authentication issues related to having them displayed. The quick fix is to only `show_in_rest` for authenticated users with the `lifterlms_instructor` cap. These are the only users who'd be able to use the block editor so it suffices to fix the leak.

However, if the REST API (our API) relies on this post type registration setting to determine if the taxonomy should be returned it causes a larger issue...

The only place I *saw* an issue was with course taxonomies. Switching it from filtering on `show_in_rest` to `public` returned the same set of taxonomies so I committed it and moved on.

I DO NOT WANT every taxonomy ever returned with the links. No. I only want the ones outlined in the spec.

If I've accidentally exposed other taxonomies I'm sorry. Let's fix that.

Perhaps intsead of trying to filter on properties of the taxononmy we can just "white list" the ones we want to display. There's only probably max 6 of them (the 4 on the course then membership cats and tags -- these 2 don't show in rest (yet) anyway so we'll still need another way to add them to the membership resource).

Does that help?

**Comment by eri-trabiccolo** [comment]
Considering that nothing in [WP_Taxonomy](https://developer.wordpress.org/reference/classes/wp_taxonomy/) forbids us to add a "custom" object property, what do you think if when registering our taxonomies (that we want to show in our rest resources) in llms core we add the key/value `'show_in_llms_rest' => true` pair to the array of args?
I see that's not completely orthodox as that won't be a declared class field but, looking at how the WP_Taxonomy `set_props()` is implemented I think what I'm proposing would be an intended feature.
Otherwise let's go with the per resource white listing.

Let me know.

**Comment by thomasplevy** [comment]
That sounds like a great solution to me
