### ISSUE TITLE
Enrollments Resource returns `string` id's instead of correct `int` values

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#77]
`post_id` and `student_id` properties are currently returned as strings.

**Comment by eri-trabiccolo** [comment]
They should be casted to int as soon as possible, I mean here:
https://github.com/gocodebox/lifterlms-rest/blob/1.0.0-beta.3/includes/server/class-llms-rest-enrollments-controller.php#L882
