### ISSUE TITLE
Lessons: question about assignment properties and link visibility

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#85]
Should the `assignment` properties (and link) be returned if the related addon is not active?
In my opinion it should be not...

What do you think?

If it should be not then it must be available in the schema ONLY IF the addon is active.

@thomasplevy ^

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

The assignment property itself will actually be implemented as an addition to the assignments add-on codebase (not as part of the rest api feature plugin itself included in the core.

The docs allude to this but don't say so explicitly so an update to the spec is in order:

> While assignment functionality is included with the LifterLMS Core REST API, the assignments themselves are implemented by the LifterLMS Assignments add-on.

We should add something like "This property is only returned when the assignments add-on plugin is activated"

**Comment by thomasplevy** [comment]
Therefore the schema and object returns in the rest api codebase *must be filterable* so the add-on can alter the schema.

**Comment by eri-trabiccolo** [comment]
Ah ok. cool!
