### ISSUE TITLE
Courses spec: enrollments/access dates should be nullable

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#87]
see 
https://github.com/gocodebox/lifterlms-rest/issues/16#issuecomment-508250705

as the `drip_date` is for the Lesson resource.

Right?

**Comment by thomasplevy** [comment]
Yes, an update to the spec is in order

**Comment by eri-trabiccolo** [comment]
Ok so I will also make a PR to make the controller follow the upcoming new spec...

**Comment by thomasplevy** [comment]
Here's how to make a property nullable:

https://github.com/gocodebox/lifterlms-rest/blob/18dd56f0344aa8e8805830fbe4d609fe1e8fb255/spec/components/schemas/Lesson.yaml#L80

Update the property in the spec for me please and include it in the PR
