### ISSUE TITLE
Delete API Keys when user is deleted

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#90]
Per core https://github.com/gocodebox/lifterlms/issues/940

**Comment by eri-trabiccolo** [comment]
It's weird for me deleting webhooks just because the user who created them has been deleted.
Do we really want this, why?

**Comment by thomasplevy** [comment]
yea maybe you're right... no one's ever reported it as an issue I was thinking about it as cleanup task when a user is removed... Some people might *expect* that the related data is also removed.

I think API keys *should* absolutely be removed as they are specific to a user. API Keys are credentials specific to a user, kind of like a password.

But you're right about webhooks. We do store the related user ID during creation though but it's never displayed or referenced anywhere after creation as far as I can recall so it's probably fine to just ignore that part of this task.
